### ISSUE TITLE
idea-plugin: manage configuration for compilation

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-meta#242]

**Comment by rachelcarmena** [comment]
There is a way to create extensions for existing plugins. I'm going to follow that idea.

**Comment by rachelcarmena** [comment]
It seems that Kotlin plugin doesn't provide a extension point for `CollectAdditionalSourcesExtension`. In fact, that interface doesn't provide an `EP_NAME` as other available extension points. I'm going to search another strategy.

**Comment by raulraja** [comment]
Maybe intercepting this:
https://github.com/JetBrains/kotlin/blob/046aa868de25964414da8f176d000983b6e0a88a/idea/resources/META-INF/plugin-common.xml#L311-L312

**Comment by raulraja** [comment]
Since that is a Project service you can get it off an instance of a project on project open like the synth cache is currently being initialized. This will allow you to get a hold of those settings and see if you can change them or access them somehow. The debugger helps as a REPL where you intercept a `project: Project` in the debug point and ask it to give you services where you can invoke their methods.

Maybe you can just get an instance here of the compiler settings and mutate them like it's done here: https://github.com/JetBrains/kotlin/blob/c0bf5a65667b762cb9d2d079eb6beb4fb06959cd/jps-plugin/jps-tests/test/org/jetbrains/kotlin/jps/build/dependeciestxt/ModulesTxt.kt#L248

**Comment by raulraja** [comment]
Here is an example that does just that. Get the service with the project and mutates the settings programmatically.

https://github.com/JetBrains/kotlin/blob/8c84f885ac3a5ec6d7d9efb268e6fc7e01c89dda/idea/idea-jvm/src/org/jetbrains/kotlin/idea/configuration/KotlinWithLibraryConfigurator.kt#L366-L373

**Comment by rachelcarmena** [comment]
Thanks @raulraja !! And it uses an available extension point: `KotlinProjectConfigurator`. Let's go!!

**Comment by rachelcarmena** [comment]
And besides `compilerSettings` with `additionalArguments`, 
there is `compilerArguments` with `pluginClasspaths` :tada:

**Comment by rachelcarmena** [comment]
* The source code to get an external dependency from `compiler-plugin` and to add it to `pluginClasspaths` is ready.
* Verified that the source code is right when checking the internal configuration with an example which includes the use of `compiler-plugin`.
* **Next step**: find the right extension point to apply the changes. For example, `gradleProjectImportHandler` extension point doesn't work because the changes about `facet.configuration.settings.compilerArguments` are not considered.

**Comment by rachelcarmena** [comment]
Found the right point. Last tests!

**Comment by rachelcarmena** [comment]
Closing because of being a wrong issue. Removing from board as well.
Action to avoid related misunderstandings: #255
