### ISSUE TITLE
Auto install idea plugin from Gradle plugin

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow-meta#245]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206163949-Doing-automatic-installation-of-plugin

**Comment by rachelcarmena** [comment]
Use case:
- A developer is using Arrow Meta Gradle Plugin in IDE without Arrow Meta IDEA plugin.
- When loading Gradle, verify if Arrow Meta IDEA plugin is installed.
- If it doesn't exist, auto install it and message to reload IDE.

**Comment by i-walker** [comment]
To provide a familiar user experience we can facilitate this extension [ `EditorNotifications.Provider<EditorNotificationPanel>`](https://github.com/JetBrains/kotlin/blob/52c00ba2a14d4fb69c9b41e137afb19d0c9de92e/idea/idea-jvm/src/org/jetbrains/kotlin/idea/configuration/KotlinSetupEnvironmentNotificationProvider.kt#L38) in order to notify and configure Arrow-Meta for the User. 
This extension is used, whenever a user opens a Kotlin Project and there is no Kotlin SDK in the Project Scope. We can provide the same workflow for applying Arrow-Meta to the Ide.

**Comment by rachelcarmena** [comment]
Awesome @i-walker , thank you very much!!

**Comment by rachelcarmena** [comment]
After reviewing API: 

* Gradle provides a method to run an external command which blocks the execution until having a result.
* However, we cannot control IDEA from Gradle Plugin. We'd need another IDEA plugin for it.
* An alternative: show a message with the link to install the plugin.

Tasks:

* [ ] How to know that the Gradle plugin is running in IDEA
* [ ] How to know that Arrow Meta is installed in the IDEA which is running (the user can be more than one instance)
* [ ] How to package Gradle plugin with a script (to run a single command). Check if it's possible.
* [ ] Run that script from Gradle plugin.

**Comment by rachelcarmena** [comment]
Idea: inspect environment variables.

**Comment by rachelcarmena** [comment]
- How to know that Gradle Plugin is running on Intellij IDEA: presence of system properties like `idea.active=true`.
- How to know the plugins directory location: `jb.vmOptionsFile` system property.
- It's not necessary to write/include an script. It will be write in Kotlin.

**Comment by rachelcarmena** [comment]
First approach: #403

**Comment by rachelcarmena** [comment]
Second approach: #409
