### ISSUE TITLE
[BUG] Meta extensions are not deregistered

### ISSUE THREAD

**Issue by jansorg** [arrow-kt/arrow-meta#659]
Branch ja-fix-quotetests
See PR #656 

1. checkout that branch
1. Run all tests of the idea-plugin module
1. Tests will fail

Running a test in isolation doesn't fail. Running all tests makes tests fail. The reason is that the [Quotesystem's extensions](https://github.com/arrow-kt/arrow-meta/blob/6b2511c9234b0797a1484fdd3fc326d100d0e114/idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/quotes/system/QuoteSystem.kt#L44) contain extensions of disposed projects.

1. Each test creates a project.
1. For each project the extensions are registered. It seems that they're kept in a global map
1. A project is disposed when a test terminates. But the extension, which references it, is still registered
1. As soon as this extension is used during another test run, this breaks the tests, because the dispose state is checked

Scope: This isn't just a problem for tests, as far as I understand. The same will happen when you open a project in an ide, work with it and close it. When you now open another project, the extensions referencing the old project should still be around.

See the disposed state of the selected project:
![Screenshot_012](https://user-images.githubusercontent.com/11473063/83887835-49c01e00-a749-11ea-9e2b-519f95a91e58.png)

**Comment by i-walker** [comment]
The issue was that previously all quote definitions were saved in a global list [here](https://github.com/arrow-kt/arrow-meta/blob/00387c575ff45c77e7b11d1a506853aa1e053c47/compiler-plugin/src/main/kotlin/arrow/meta/quotes/Quote.kt#L165) and that accumulated all quotes without a proper scope or lifecycle. 
The proposed changes in #661 align the quote definition in the lifecycle of the CompilerContext, which is available in the Ide as a service.

This was unrelated to the registration mechanism in IdeRegistry for ExtensionPhases.
As always thanks for reporting :D 🎉
