### ISSUE TITLE
[BUG] Arrow Meta plugin is incompatible with idea 2020.2.

### ISSUE THREAD

**Issue by MairwunNx** [arrow-kt/arrow-meta#732]
**Describe the bug**
I tried install via local zip file and via gradle task, in both ways it's don't work with `2020.2`.

**Expected behavior**
Must work with last stable release of IDEA.

**Screenshots**

![image](https://user-images.githubusercontent.com/39625750/90977588-36a23a80-e54f-11ea-91d6-9766ffb0f649.png)

**Environment:**
- Intellij IDEA version: 2020.2

**Comment by i-walker** [comment]
Please, 
download a compatible Ide version with the Kotlin Plugin 1.3.61.

Each Ide plugin defines the version it is compatible with here https://github.com/arrow-kt/arrow-meta/blob/d427ec9cb3fb457eedc9ab9d2c917dd0140d298f/idea-plugin/build.gradle#L48. 
And we're following to be compatible with the Kotlin Plugin, we depend on, and it's compatibility range. In master that is this version [1.3.61-release-IJ2019.3-1](https://github.com/arrow-kt/arrow-meta/blob/d427ec9cb3fb457eedc9ab9d2c917dd0140d298f/gradle.properties#L7)

I am closing this because we're working on updating to 1.4.0 in a development branch. 
If you have any questions or need help with setting up Meta in your Ide. Feel free to ask in the kotlin slack channel #arrow-meta or reach out to me or other maintainers. We'll be happy to assist :D
